name: ci

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache stack global package db
      id:   stack-global
      uses: actions/cache@v3
      env:
        cache-name: stack-global
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Cache stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache@v3
      env:
        cache-name: stack-programs
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Cache .stack-work
      uses: actions/cache@v3
      env:
        cache-name: stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install stack
      run: |
          mkdir -p ~/.local/bin
          export PATH=~/.local/bin:$PATH
          # curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack
          if [[ ! -x ~/.local/bin/stack ]]; then curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
          stack --version

    - name: Install GHC
      run: |
        stack setup --install-ghc

    - name: Install haskell deps
      run: |
        stack build --test --bench --only-dependencies --dry-run
        stack build --test --bench --only-dependencies

    - name: Build project
      run: |
        stack build

    - name: Run tests
      run: |
        stack test
